import { PDFDocument, StandardFonts, rgb, PDFPage } from 'pdf-lib';
import QRCode from 'qrcode';

const margin = 50;
const lineHeight = 14;

// Helper: split long text into wrapped lines
function splitTextIntoLines(text: string, maxCharsPerLine: number): string[] {
  if (!text) return [];
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const w of words) {
    const test = current ? current + ' ' + w : w;
    if (test.length <= maxCharsPerLine) {
      current = test;
    } else {
      lines.push(current);
      current = w;
    }
  }
  if (current) lines.push(current);
  return lines;
}

// Draw header section with underline
function drawSectionHeader(page: PDFPage, text: string, x: number, y: number, size: number, font: any) {
  page.drawText(text, { x, y, size, font });
  const width = font.widthOfTextAtSize(text, size);
  page.drawLine({
    start: { x, y: y - 3 },
    end: { x: x + width, y: y - 3 },
    thickness: 0.8,
    color: rgb(0, 0, 0),
  });
  return y - 24;
}

// Draw a transcript section with pagination
function drawTranscriptSection(
  pdfDoc: PDFDocument,
  page: PDFPage,
  text: string,
  y: number,
  opts: { font: any; boldFont: any; margin?: number; title?: string }
) {
  const { font, boldFont, margin = 50, title = 'TRANSCRIPT' } = opts;
  let currentPage = page;
  let currentY = y;

  currentY = drawSectionHeader(currentPage, title, margin, currentY, 12, boldFont);

  const lines = splitTextIntoLines(text, 90);
  for (const line of lines) {
    if (currentY < 50) {
      currentPage = pdfDoc.addPage([612, 792]);
      currentY = 750;
      currentY = drawSectionHeader(currentPage, `${title} (continued)`, margin, currentY, 12, boldFont);
    }
    currentPage.drawText(line, {
      x: margin,
      y: currentY,
      size: 10,
      font,
      lineHeight,
    });
    currentY -= lineHeight;
  }

  return { page: currentPage, y: currentY };
}

// Draw footer with page numbers and confidentiality
function addFooter(page: PDFPage, pageNumber: number, totalPages: number, font: any) {
  const footerY = 30;
  page.drawLine({
    start: { x: margin, y: footerY + 10 },
    end: { x: page.getWidth() - margin, y: footerY + 10 },
    thickness: 0.5,
    color: rgb(0.5, 0.5, 0.5),
  });
  page.drawText(`Page ${pageNumber} of ${totalPages}`, {
    x: page.getWidth() - margin - 70,
    y: footerY,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
  page.drawText(`Generated by ProofAI • Confidential & Secure`, {
    x: margin,
    y: footerY,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
}

// Draw signature area at bottom (safe ASCII characters only)
function drawSignatureArea(page: PDFPage, y: number, font: any, boldFont: any) {
  let currentY = y;
  currentY -= 50; // spacing before signature

  page.drawLine({
    start: { x: margin, y: currentY },
    end: { x: margin + 200, y: currentY },
    thickness: 1,
    color: rgb(0, 0, 0),
  });

  currentY -= 15;
  page.drawText('Authorized Signature', { x: margin, y: currentY, size: 10, font: boldFont });

  currentY -= 20;
  // ✅ Plain hyphen to avoid encoding issues
  page.drawText('ProofAI System Auto-Signature', {
    x: margin,
    y: currentY,
    size: 12,
    font,
    color: rgb(0.2, 0.2, 0.2),
  });

  return currentY - 30;
}

// Embed QR code
async function embedQRCode(pdfDoc: PDFDocument, page: PDFPage, url: string, yOffset: number) {
  const qrDataUrl = await QRCode.toDataURL(url, { margin: 0, scale: 4 });
  const qrImageBytes = await fetch(qrDataUrl).then((r) => r.arrayBuffer());
  const qrImage = await pdfDoc.embedPng(qrImageBytes);
  const qrSize = 120;
  const qrX = (page.getWidth() - qrSize) / 2;
  const qrY = yOffset - qrSize - 10;
  page.drawText('SCAN TO VIEW EVIDENCE', { x: qrX - 20, y: qrY + qrSize + 10, size: 12 });
  page.drawImage(qrImage, { x: qrX, y: qrY, width: qrSize, height: qrSize });
}

export async function generatePDF(inputData: any) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([612, 792]);
  let y = 750;

  const caseId = inputData.caseId || 'Unknown';
  const location = inputData.location || 'Unknown Location';
  const now = new Date();
  const dateTime = now.toLocaleString(); // date + time

  // Header with location, case ID, and date-time
  page.drawText(`LOCATION: ${location}`, { x: margin, y, size: 12, font: boldFont });
  y -= 25;
  page.drawText(`CASE REPORT`, { x: margin, y, size: 14, font: boldFont });
  y -= 25;
  page.drawText(`Case ID: ${caseId}`, { x: margin, y, size: 12, font });
  y -= 15;
  page.drawText(`Report Date: ${dateTime}`, { x: margin, y, size: 12, font });
  y -= 25;
  page.drawLine({ start: { x: margin, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 20;

  let currentPage = page;
  let currentY = y;

  const translatedTranscript: string = inputData.translatedTranscript || '';
  const originalTranscript: string = inputData.originalTranscript || inputData.transcript || '';

  // ENGLISH TRANSLATION
  if (translatedTranscript.trim().length > 0) {
    const res = drawTranscriptSection(pdfDoc, currentPage, translatedTranscript, currentY, {
      font,
      boldFont,
      title: 'ENGLISH TRANSLATION',
    });
    currentPage = res.page;
    currentY = res.y - 30;
  } else {
    currentPage.drawText('No English translation available', {
      x: margin,
      y: currentY,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    currentY -= 30;
  }

  currentY = Math.max(60, currentY - 20);

  if (currentY < 100) {
    currentPage = pdfDoc.addPage([612, 792]);
    currentY = 750;
  }

  // ORIGINAL TRANSCRIPT
  if (originalTranscript.trim().length > 0) {
    const res = drawTranscriptSection(pdfDoc, currentPage, originalTranscript, currentY, {
      font,
      boldFont,
      title: 'ORIGINAL TRANSCRIPT (es)',
    });
    currentPage = res.page;
    currentY = res.y - 30;
  } else {
    currentY = drawSectionHeader(currentPage, 'ORIGINAL TRANSCRIPT (es)', margin, currentY, 12, boldFont) - 10;
    currentPage.drawText('No original transcript available', {
      x: margin,
      y: currentY,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    currentY -= 30;
  }

  // Signature area
  currentY = drawSignatureArea(currentPage, currentY, font, boldFont);

  // QR code
  await embedQRCode(pdfDoc, currentPage, inputData.videoUrl || 'https://proof.ai', currentY);

  // Footer on all pages
  const pages = pdfDoc.getPages();
  pages.forEach((p, i) => addFooter(p, i + 1, pages.length, font));

  return await pdfDoc.save();
}
